// Generated by wasm-pass; edit at your own risk!

const util = require("util");

/**
 * @template T
 * @param {T} EnumType
 * @param {number} value
 * @returns {T}
 */
function createEnumValue(EnumType, value) {
    const lit = new EnumType();
    lit.value = value;
    return lit;
}

/**
 * @param {Object|Function} value
 * @returns {number}
 */
function sizeOf(value) {
    if (typeof value === "object" || typeof value === "function") {
        return value.__size;
    }

    throw new Error("Value has unknown size!");
}

class Enum {
    /** @type {number} */
    value;

    constructor() {
        if (arguments.length !== 0) throw new Error(`Use ${this.constructor.name}.from(number)!`);
    }

    static getVariants() {
        return Object.entries(this).slice(this.__constant_count + 2 /* account for __size and __constant_count */);
    }

    /** @param {number} value */
    static from(value) {
        for (const [_, tag] of this.getVariants()) {
            if (tag.value === value) return tag;
        }

        const val = new this();
        val.value = value;
        return val;
    }

    toString() {
        for (const [name, tag] of this.constructor.getVariants()) {
            if (tag.value === this.value) return `${this.constructor.name}.${name}`;
        }

        return `${this.constructor.name}(${this.value})`;
    }

    [util.inspect.custom]() {
        return this.toString();
    }
}

class Struct {}

class Allocator {
    allocBytes;
    freeBytes;

    /** @param {WebAssembly.Exports} exports */
    constructor(exports) {
        this.allocBytes = exports.allocBytes;
        this.freeBytes = exports.freeBytes;
    }

    /**
     * @param {Object} type
     * @param {number} len
     * @returns {Slice}
     */
    alloc(type, len) {
        // @ts-ignore
        return new Slice(type, len, this.allocBytes(sizeOf(type) * len));
    }

    /** @param {Slice} slice */
    free(slice) {
        // @ts-ignore
        this.freeBytes(slice.ptr, sizeOf(slice.type) * slice.len);
    }
}

/** @param {WebAssembly.Instance} instance */
module.exports = function bind(instance) {
    let view = new DataView(instance.exports.memory.buffer);

    function getDataView() {
        // When view.buffer.byteLength is 0, the memory buffer was resized and needs to be refreshed.
        return view.buffer.byteLength === 0 ? (view = new DataView(instance.exports.memory.buffer)) : view;
    }

    /// BINDINGS
    return bindings;
};

module.exports.Allocator = Allocator;
module.exports.Struct = Struct;
module.exports.sizeOf = sizeOf;
module.exports.Enum = Enum;
